# Site settings
author: SDK 
title: Baking Bits
header-img: img/home-bg.png
email: sdk1270@gmail.com
copyright_name: SDK 
description: > # this means to ignore newlines until "baseurl:"
  Code + cooking 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thisisSDK

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
